sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t prod .

script:
  - docker run prod npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-501352840692"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_ID"
  secret_access_key:
    secure: "$AWS_ACCESS_PWD"  